#This is a Makefile for Project2.java
#Java Compiler
JC = javac
#To run java program
JR = java
#Source Folder
SF = ../src/
#Program file names
PROG = ${SF}Driver
PROG2 = ${SF}ScheduleAlgorithm
PROG3 = ${SF}Process

#To compile the program
all:
	$(JC) $(PROG).java

#To clear all Java class files
clr:
	rm -f *.class

#To view the program
cat:
	cat $(PROG).java
	cat $(PROG2).java
	cat $(PROG3).java
